In [1]:
#import numpy library

import numpy as np


# creating an array 

In [3]:
neighbour_country=np.array(["pakistan","india","Afghanistan","Iran"])
neighbour_country

array(['pakistan', 'india', 'Afghanistan', 'Iran'], dtype='<U11')

In [4]:
type(neighbour_country)

numpy.ndarray

In [5]:
len(neighbour_country)

4

In [11]:
neighbour_country[1:3]

array(['india', 'Afghanistan'], dtype='<U11')

In [16]:
#array of zeros

np.zeros(23)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.empty([2,2])

array([[0., 0.],
       [0., 0.]])

In [25]:
a=np.arange(0,15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.arange(2,55,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54])

In [28]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

In [29]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [30]:
mult=a*2
mult

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [33]:
mult=a*(2+3)
mult

array([[ 5, 10, 15],
       [20, 25, 30]])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
array_mult=a*b
array_mult

array([[10, 22, 36],
       [52, 70, 90]])

In [37]:
i=np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Determinant of a matrix

In [19]:
import numpy as np
A= np.array([x for x in range(4)])


In [14]:
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [20]:
A=A.reshape(2,2)

In [21]:
print(A)

[[0 1]
 [2 3]]


In [17]:
A[0]

array([0, 1, 2, 3])

In [22]:
det = np.linalg.det(A)
det

-2.0

In [31]:
np.random.seed(200)
A= np.random.randint(0, 50, size = (5,5))
A

array([[26, 41, 16,  4, 42],
       [12, 15, 25, 14, 27],
       [25, 11,  6, 42,  1],
       [ 7, 27,  9, 15,  1],
       [46, 23, 21, 24,  7]])

In [32]:
np.random.seed(100)
B= np.random.randint(0, 50, size = (5,5))
B

array([[ 8, 24,  3, 39, 23],
       [15, 48, 10, 30, 34],
       [ 2, 34, 14, 34, 49],
       [48, 24, 15, 36, 43],
       [16,  9, 29, 22,  2]])

In [34]:
Mult=np.matmul(A,B)
Mult

array([[1719, 3610, 1990, 3856, 3032],
       [1475, 2437, 1529, 2866, 2667],
       [2409, 2349,  928, 3043, 3051],
       [1215, 2139,  671, 1951, 2167],
       [2019, 3561, 1225, 4216, 3915]])

In [41]:

#Transpose
OneD=Mult.T
OneD

array([[1719, 1475, 2409, 1215, 2019],
       [3610, 2437, 2349, 2139, 3561],
       [1990, 1529,  928,  671, 1225],
       [3856, 2866, 3043, 1951, 4216],
       [3032, 2667, 3051, 2167, 3915]])

In [46]:
import numpy as np
arr_d = (np.asarray(OneD)).flatten()
arr_d

array([1719, 1475, 2409, 1215, 2019, 3610, 2437, 2349, 2139, 3561, 1990,
       1529,  928,  671, 1225, 3856, 2866, 3043, 1951, 4216, 3032, 2667,
       3051, 2167, 3915])

In [47]:
arr_d.sort()

In [48]:
arr_d

array([ 671,  928, 1215, 1225, 1475, 1529, 1719, 1951, 1990, 2019, 2139,
       2167, 2349, 2409, 2437, 2667, 2866, 3032, 3043, 3051, 3561, 3610,
       3856, 3915, 4216])

In [51]:
indexes = np.argsort(arr_d)
indexes

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24], dtype=int64)